load("//bazel:copts.bzl", "DEFAULT_COPTS", "TEST_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "utils_lib",
  srcs = [
    "utils.h",
    "utils.cc",
    "time_utils.h",
    "time_utils.cc",
  ],
  copts = DEFAULT_COPTS,
)


cc_library(
  name = "file_utils_lib",
  srcs = [
    "file_utils.h",
    "file_utils.cc",
  ],
  copts = DEFAULT_COPTS,
)