load("//bazel:copts.bzl", "DEFAULT_COPTS", "TEST_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "utils_lib",
  srcs = [
    "utils.h",
    "utils.cc",
  ],
  copts = DEFAULT_COPTS,
)