load("//bazel:copts.bzl", "DEFAULT_COPTS", "TEST_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "init_target_interface",
  srcs = [
    "init_target.h",
  ],
  copts = DEFAULT_COPTS,
)

cc_library(
  name = "init_target_registry_lib",
  srcs = [
    "init_target_registry.h",
  ],
  copts = DEFAULT_COPTS,
)
