load("//bazel:copts.bzl", "DEFAULT_COPTS", "TEST_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "transport_constants",
    copts = DEFAULT_COPTS,
    srcs = [
        "constants.h",
    ],
    visibility = ["//visibility:public"],
)